Deal with deprecated @extend syntax
Errors:
```
SassError: SassError: compound selectors may no longer be extended.
Consider `@extend a, :hover` instead.
See http://bit.ly/ExtendCompound for details.
```